Repository theseus-rs/postgresql-embedded, pull requests merged in 2024-05, with the labels that each got.

#58 fix: create extract_dir on same filesystem as out_dir
  postgresql_archive/src/archive.rs
Labels: fix

#62 chore: update dependencies
  Cargo.lock
  postgresql_archive/src/archive.rs
Labels: dependencies, internal

#65 build: correct lint warnings
  .github/workflows/checks.yml
  Cargo.lock
  postgresql_archive/benches/archive.rs
  postgresql_commands/src/clusterdb.rs
  postgresql_commands/src/createdb.rs
  postgresql_commands/src/createuser.rs
  postgresql_commands/src/dropdb.rs
  postgresql_commands/src/dropuser.rs
  postgresql_commands/src/ecpg.rs
  postgresql_commands/src/initdb.rs
  postgresql_commands/src/oid2name.rs
  postgresql_commands/src/pg_amcheck.rs
  postgresql_commands/src/pg_archivecleanup.rs
  postgresql_commands/src/pg_basebackup.rs
  postgresql_commands/src/pg_checksums.rs
  postgresql_commands/src/pg_config.rs
  postgresql_commands/src/pg_controldata.rs
  postgresql_commands/src/pg_ctl.rs
  postgresql_commands/src/pg_dump.rs
  postgresql_commands/src/pg_dumpall.rs
  postgresql_commands/src/pg_isready.rs
  postgresql_commands/src/pg_receivewal.rs
  postgresql_commands/src/pg_recvlogical.rs
  postgresql_commands/src/pg_resetwal.rs
  postgresql_commands/src/pg_restore.rs
  postgresql_commands/src/pg_rewind.rs
  postgresql_commands/src/pg_test_fsync.rs
  postgresql_commands/src/pg_test_timing.rs
  postgresql_commands/src/pg_upgrade.rs
  postgresql_commands/src/pg_verifybackup.rs
  postgresql_commands/src/pg_waldump.rs
  postgresql_commands/src/pgbench.rs
  postgresql_commands/src/postgres.rs
  postgresql_commands/src/psql.rs
  postgresql_commands/src/reindexdb.rs
  postgresql_commands/src/traits.rs
  postgresql_commands/src/vacuumdb.rs
  postgresql_commands/src/vacuumlo.rs
  postgresql_embedded/tests/postgresql.rs
Labels: build

#66 test: improve test coverage
  postgresql_archive/src/error.rs
  postgresql_archive/src/version.rs
  postgresql_embedded/src/error.rs
Labels: internal

#71 feat: add native-tls support
  Cargo.lock
  postgresql_archive/Cargo.toml
  postgresql_archive/README.md
  postgresql_embedded/Cargo.toml
  postgresql_embedded/README.md
Labels: enhancement
