Repository theseus-rs/postgresql-embedded, pull requests merged in 2024-09, with the labels that each got.

#133 chore: switch from xz2 to liblzma
  .gitignore
  Cargo.lock
  Cargo.toml
  postgresql_archive/Cargo.toml
  postgresql_archive/src/extractor/tar_xz_extractor.rs
Labels: internal

#134 chore: update dependencies
  Cargo.lock
  Cargo.toml
Labels: internal

#135 fix: allow archives to be bundled from alternate github repositories
  README.md
  postgresql_archive/tests/zonky.rs
  postgresql_embedded/Cargo.toml
  postgresql_embedded/build/bundle.rs
Labels: fix

#136 chore: forbid clippy allow attributes
  Cargo.lock
  Cargo.toml
  examples/archive_async/src/main.rs
  examples/archive_sync/src/main.rs
  examples/axum_embedded/src/main.rs
  examples/diesel_embedded/src/main.rs
  examples/download_progress_bar/src/main.rs
  examples/embedded_async/src/main.rs
  examples/embedded_sync/src/main.rs
  examples/portal_corp_extension/src/main.rs
  examples/postgres_embedded/src/main.rs
  examples/sqlx_embedded/src/main.rs
  examples/tensor_chord_extension/src/main.rs
  examples/zonky/src/main.rs
  postgresql_archive/src/archive.rs
  postgresql_archive/src/blocking/archive.rs
  postgresql_archive/src/configuration/theseus/extractor.rs
  postgresql_archive/src/configuration/theseus/matcher.rs
  postgresql_archive/src/configuration/zonky/extractor.rs
  postgresql_archive/src/configuration/zonky/matcher.rs
  postgresql_archive/src/configuration/zonky/repository.rs
  postgresql_archive/src/extractor/registry.rs
  postgresql_archive/src/extractor/tar_gz_extractor.rs
  postgresql_archive/src/extractor/tar_xz_extractor.rs
  postgresql_archive/src/extractor/zip_extractor.rs
  postgresql_archive/src/hasher/registry.rs
  postgresql_archive/src/lib.rs
  postgresql_archive/src/matcher/registry.rs
  postgresql_archive/src/repository/github/repository.rs
  postgresql_archive/src/repository/maven/repository.rs
  postgresql_archive/src/repository/registry.rs
  postgresql_archive/tests/blocking.rs
  postgresql_commands/src/initdb.rs
  postgresql_commands/src/lib.rs
  postgresql_commands/src/pg_amcheck.rs
  postgresql_commands/src/pg_basebackup.rs
  postgresql_commands/src/pg_dump.rs
  postgresql_commands/src/pg_dumpall.rs
  postgresql_commands/src/pg_restore.rs
  postgresql_commands/src/pgbench.rs
  postgresql_commands/src/postgres.rs
  postgresql_commands/src/psql.rs
  postgresql_commands/src/vacuumdb.rs
  postgresql_embedded/src/lib.rs
  postgresql_embedded/src/settings.rs
  postgresql_extensions/src/extensions.rs
  postgresql_extensions/src/lib.rs
  postgresql_extensions/src/matcher.rs
  postgresql_extensions/src/repository/portal_corp/repository.rs
  postgresql_extensions/src/repository/registry.rs
  postgresql_extensions/src/repository/steampipe/extensions.rs
  postgresql_extensions/src/repository/steampipe/repository.rs
  postgresql_extensions/src/repository/tensor_chord/repository.rs
  rust-toolchain.toml
Labels: internal

#138 feat: add version 17 support
  postgresql_embedded/src/lib.rs
  postgresql_extensions/tests/blocking.rs
  postgresql_extensions/tests/extensions.rs
Labels: enhancement

#139 depr!: remove version 12 and deprecate version 13
  postgresql_embedded/src/lib.rs
Labels: breaking, deprecation
