Repository theseus-rs/postgresql-embedded, pull requests merged in 2024-06, with the labels that each got.

#72 fix: don't require rustls for the build script. only enable by default.
  postgresql_embedded/Cargo.toml
Labels: fix

#74 feat!: add ability to specify multiple pg_ctl options and define server configuration in Settings
  Cargo.lock
  deny.toml
  postgresql_commands/src/pg_ctl.rs
  postgresql_embedded/src/postgresql.rs
  postgresql_embedded/src/settings.rs
  postgresql_embedded/tests/start_config.rs
Labels: enhancement, breaking

#76 fix: correct errors when PGDATABASE envar is set
  Cargo.lock
  postgresql_commands/src/clusterdb.rs
  postgresql_commands/src/createdb.rs
  postgresql_commands/src/createuser.rs
  postgresql_commands/src/dropdb.rs
  postgresql_commands/src/dropuser.rs
  postgresql_commands/src/ecpg.rs
  postgresql_commands/src/error.rs
  postgresql_commands/src/initdb.rs
  postgresql_commands/src/lib.rs
  postgresql_commands/src/oid2name.rs
  postgresql_commands/src/pg_amcheck.rs
  postgresql_commands/src/pg_archivecleanup.rs
  postgresql_commands/src/pg_basebackup.rs
  postgresql_commands/src/pg_checksums.rs
  postgresql_commands/src/pg_config.rs
  postgresql_commands/src/pg_controldata.rs
  postgresql_commands/src/pg_ctl.rs
  postgresql_commands/src/pg_dump.rs
  postgresql_commands/src/pg_dumpall.rs
  postgresql_commands/src/pg_isready.rs
  postgresql_commands/src/pg_receivewal.rs
  postgresql_commands/src/pg_recvlogical.rs
  postgresql_commands/src/pg_resetwal.rs
  postgresql_commands/src/pg_restore.rs
  postgresql_commands/src/pg_rewind.rs
  postgresql_commands/src/pg_test_fsync.rs
  postgresql_commands/src/pg_test_timing.rs
  postgresql_commands/src/pg_upgrade.rs
  postgresql_commands/src/pg_verifybackup.rs
  postgresql_commands/src/pg_waldump.rs
  postgresql_commands/src/pgbench.rs
  postgresql_commands/src/postgres.rs
  postgresql_commands/src/psql.rs
  postgresql_commands/src/reindexdb.rs
  postgresql_commands/src/traits.rs
  postgresql_commands/src/vacuumdb.rs
  postgresql_commands/src/vacuumlo.rs
  postgresql_embedded/src/postgresql.rs
  postgresql_embedded/tests/environment_variables.rs
Labels: fix

#77 build: Enable pedantic lints
  postgresql_archive/src/archive.rs
  postgresql_archive/src/blocking/mod.rs
  postgresql_archive/src/lib.rs
  postgresql_archive/src/version.rs
  postgresql_embedded/src/blocking/mod.rs
  postgresql_embedded/src/error.rs
  postgresql_embedded/src/lib.rs
  postgresql_embedded/src/postgresql.rs
  postgresql_embedded/src/settings.rs
Labels: build

#78 test: add missing command error tests and clean up lint directives
  .github/workflows/ci.yml
  Cargo.lock
  examples/archive_async/src/main.rs
  examples/archive_sync/src/main.rs
  examples/embedded_async/src/main.rs
  examples/embedded_sync/src/main.rs
  examples/postgres_embedded/src/main.rs
  examples/sqlx_embedded/src/main.rs
  postgresql_commands/src/clusterdb.rs
  postgresql_commands/src/createdb.rs
  postgresql_commands/src/createuser.rs
  postgresql_commands/src/dropdb.rs
  postgresql_commands/src/dropuser.rs
  postgresql_commands/src/ecpg.rs
  postgresql_commands/src/initdb.rs
  postgresql_commands/src/lib.rs
  postgresql_commands/src/oid2name.rs
  postgresql_commands/src/pg_amcheck.rs
  postgresql_commands/src/pg_archivecleanup.rs
  postgresql_commands/src/pg_basebackup.rs
  postgresql_commands/src/pg_checksums.rs
  postgresql_commands/src/pg_config.rs
  postgresql_commands/src/pg_ctl.rs
  postgresql_commands/src/pg_dump.rs
  postgresql_commands/src/pg_dumpall.rs
  postgresql_commands/src/pg_receivewal.rs
  postgresql_commands/src/pg_recvlogical.rs
  postgresql_commands/src/pg_resetwal.rs
  postgresql_commands/src/pg_restore.rs
  postgresql_commands/src/pg_rewind.rs
  postgresql_commands/src/pg_test_fsync.rs
  postgresql_commands/src/pg_test_timing.rs
  postgresql_commands/src/pg_upgrade.rs
  postgresql_commands/src/pg_verifybackup.rs
  postgresql_commands/src/pg_waldump.rs
  postgresql_commands/src/pgbench.rs
  postgresql_commands/src/postgres.rs
  postgresql_commands/src/psql.rs
  postgresql_commands/src/reindexdb.rs
  postgresql_commands/src/traits.rs
  postgresql_commands/src/vacuumdb.rs
  postgresql_commands/src/vacuumlo.rs
  postgresql_embedded/src/postgresql.rs
Labels: internal

#79 docs: update documentation
  README.md
  postgresql_embedded/README.md
  postgresql_embedded/tests/environment_variables.rs
Labels: documentation

#80 feat!: allow releases URL to be configured
  README.md
  examples/archive_async/src/main.rs
  examples/archive_sync/src/main.rs
  postgresql_archive/benches/archive.rs
  postgresql_archive/src/archive.rs
  postgresql_archive/src/blocking/archive.rs
  postgresql_archive/src/blocking/mod.rs
  postgresql_archive/src/lib.rs
  postgresql_archive/tests/archive.rs
  postgresql_archive/tests/blocking.rs
  postgresql_embedded/README.md
  postgresql_embedded/build/bundle.rs
  postgresql_embedded/src/blocking/mod.rs
  postgresql_embedded/src/blocking/postgresql.rs
  postgresql_embedded/src/postgresql.rs
  postgresql_embedded/src/settings.rs
Labels: enhancement, breaking

#81 feat: export Version to improve dx
  postgresql_embedded/src/lib.rs
Labels: enhancement

#82 refactor!: move version from PostgreSQL::new() to Settings
  postgresql_embedded/src/blocking/postgresql.rs
  postgresql_embedded/src/postgresql.rs
  postgresql_embedded/src/settings.rs
  postgresql_embedded/tests/postgresql.rs
  postgresql_embedded/tests/start_config.rs
Labels: breaking, internal

#84 build: unpin dependencies
  Cargo.lock
  Cargo.toml
Labels: build

#85 feat!: add semantic versioning, configurable repositories and asset matchers
  Cargo.lock
  Cargo.toml
  examples/archive_async/src/main.rs
  examples/archive_sync/src/main.rs
  postgresql_archive/Cargo.toml
  postgresql_archive/README.md
  postgresql_archive/benches/archive.rs
  postgresql_archive/src/archive.rs
  postgresql_archive/src/blocking/archive.rs
  postgresql_archive/src/blocking/mod.rs
  postgresql_archive/src/error.rs
  postgresql_archive/src/lib.rs
  postgresql_archive/src/matcher/default.rs
  postgresql_archive/src/matcher/mod.rs
  postgresql_archive/src/matcher/postgresql_binaries.rs
  postgresql_archive/src/matcher/registry.rs
  postgresql_archive/src/repository/github/mod.rs
  postgresql_archive/src/repository/github/models.rs
  postgresql_archive/src/repository/github/repository.rs
  postgresql_archive/src/repository/mod.rs
  postgresql_archive/src/repository/model.rs
  postgresql_archive/src/repository/registry.rs
  postgresql_archive/src/version.rs
  postgresql_archive/tests/archive.rs
  postgresql_archive/tests/blocking.rs
  postgresql_embedded/Cargo.toml
  postgresql_embedded/build/bundle.rs
  postgresql_embedded/src/blocking/postgresql.rs
  postgresql_embedded/src/error.rs
  postgresql_embedded/src/lib.rs
  postgresql_embedded/src/postgresql.rs
  postgresql_embedded/src/settings.rs
Labels: enhancement, breaking

#86 feat!: add configurable hashers
  postgresql_archive/src/hasher/mod.rs
  postgresql_archive/src/hasher/registry.rs
  postgresql_archive/src/hasher/sha2_256.rs
  postgresql_archive/src/lib.rs
  postgresql_archive/src/matcher/mod.rs
  postgresql_archive/src/matcher/registry.rs
  postgresql_archive/src/repository/github/repository.rs
Labels: enhancement, breaking

#87 feat: add sha2-512 support
  Cargo.lock
  postgresql_archive/src/hasher/mod.rs
  postgresql_archive/src/hasher/registry.rs
  postgresql_archive/src/hasher/sha2_512.rs
  postgresql_archive/src/repository/github/repository.rs
Labels: enhancement

#88 feat: add blake2 and sha3 hash support
  Cargo.lock
  Cargo.toml
  postgresql_archive/Cargo.toml
  postgresql_archive/src/hasher/blake2b_512.rs
  postgresql_archive/src/hasher/blake2s_256.rs
  postgresql_archive/src/hasher/mod.rs
  postgresql_archive/src/hasher/registry.rs
  postgresql_archive/src/hasher/sha3_256.rs
  postgresql_archive/src/hasher/sha3_512.rs
Labels: enhancement

#89 refactor!: remove bytes dependency
  Cargo.lock
  Cargo.toml
  postgresql_archive/Cargo.toml
  postgresql_archive/benches/archive.rs
  postgresql_archive/src/archive.rs
  postgresql_archive/src/blocking/archive.rs
  postgresql_archive/src/hasher/registry.rs
  postgresql_archive/src/repository/github/repository.rs
  postgresql_embedded/Cargo.toml
  postgresql_embedded/src/postgresql.rs
Labels: breaking, internal

#90 fix: convert possible panics to errors
  postgresql_archive/src/error.rs
  postgresql_archive/src/hasher/registry.rs
  postgresql_archive/src/matcher/registry.rs
  postgresql_archive/src/repository/github/repository.rs
  postgresql_archive/src/repository/registry.rs
Labels: fix

#91 feat: add hasher and matcher supports function
  examples/archive_async/src/main.rs
  examples/archive_sync/src/main.rs
  postgresql_archive/benches/archive.rs
  postgresql_archive/src/archive.rs
  postgresql_archive/src/error.rs
  postgresql_archive/src/hasher/registry.rs
  postgresql_archive/src/lib.rs
  postgresql_archive/src/matcher/mod.rs
  postgresql_archive/src/matcher/registry.rs
  postgresql_archive/src/matcher/target_os_arch.rs
  postgresql_archive/src/repository/github/repository.rs
  postgresql_archive/src/repository/registry.rs
  postgresql_archive/tests/archive.rs
  postgresql_archive/tests/blocking.rs
  postgresql_embedded/build/bundle.rs
  postgresql_embedded/src/settings.rs
Labels: enhancement

#94 feat: add SHA1 hash support for older Maven repositories
  Cargo.lock
  Cargo.toml
  postgresql_archive/Cargo.toml
  postgresql_archive/src/hasher/mod.rs
  postgresql_archive/src/hasher/registry.rs
  postgresql_archive/src/hasher/sha1.rs
  postgresql_archive/src/repository/maven/repository.rs
Labels: enhancement
